# Generated by Django 5.2.8 on 2025-12-04 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Ngày thu')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='Số tiền thu')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='agencies.agency', verbose_name='Đại lý')),
                ('received_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người thu')),
            ],
            options={
                'verbose_name': 'Phiếu thu tiền',
                'verbose_name_plural': 'Danh sách phiếu thu tiền',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
