# Generated by Django 5.2.8 on 2025-12-04 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã quy định')),
                ('name', models.CharField(max_length=200, verbose_name='Tên quy định')),
                ('value', models.CharField(max_length=100, verbose_name='Giá trị')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_regulations', to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Quy định',
                'verbose_name_plural': 'Danh sách quy định',
            },
        ),
        migrations.CreateModel(
            name='DebtReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('opening_debt', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Nợ đầu')),
                ('incurred', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Phát sinh')),
                ('paid', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Đã thu')),
                ('closing_debt', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Nợ cuối')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_reports', to='agencies.agency', verbose_name='Đại lý')),
            ],
            options={
                'verbose_name': 'Báo cáo công nợ',
                'verbose_name_plural': 'Danh sách báo cáo công nợ',
                'ordering': ['-year', '-month'],
                'unique_together': {('agency', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(verbose_name='Tháng')),
                ('year', models.IntegerField(verbose_name='Năm')),
                ('order_count', models.IntegerField(default=0, verbose_name='Số phiếu xuất')),
                ('total_revenue', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Tổng doanh thu')),
                ('ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Tỷ lệ (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_reports', to='agencies.agency', verbose_name='Đại lý')),
            ],
            options={
                'verbose_name': 'Báo cáo doanh số',
                'verbose_name_plural': 'Danh sách báo cáo doanh số',
                'ordering': ['-year', '-month'],
                'unique_together': {('agency', 'month', 'year')},
            },
        ),
    ]
