# Generated by Django 5.2.8 on 2025-12-04 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên loại đại lý')),
                ('max_debt', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Công nợ tối đa')),
            ],
            options={
                'verbose_name': 'Loại đại lý',
                'verbose_name_plural': 'Danh sách loại đại lý',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên quận')),
            ],
            options={
                'verbose_name': 'Quận',
                'verbose_name_plural': 'Danh sách quận',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên đại lý')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('current_debt', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Công nợ hiện tại')),
                ('reception_date', models.DateField(verbose_name='Ngày tiếp nhận')),
                ('is_active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agency_profile', to=settings.AUTH_USER_MODEL, verbose_name='Tài khoản')),
                ('agency_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='agencies.agencytype', verbose_name='Loại đại lý')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='agencies.district', verbose_name='Quận')),
            ],
            options={
                'verbose_name': 'Đại lý',
                'verbose_name_plural': 'Danh sách đại lý',
                'ordering': ['-created_at'],
            },
        ),
    ]
